### PR TITLE
Bitmap Unit Tests and Absolute to Relative Area Coordinates Fix

### PR DESCRIPTION
**Pull request by ThatRubenAguilar**
Instead of trying to dump everything into TestApp I added unit tests to cover some basic things and things we've fixed. This way TestApp can continue to serve the general positive smoke test purpose it had in the beginning. This also contains a bug fix for Phash.Bitmaps.

Let me know if there are any changes you'd like to discuss.

### CODE REVIEW

**Comment by pgrho** [comment]
I have doubts about the license of the test data. I don't know where phash test data are from and what license applied to them, but I found [one image in Flickr](https://www.flickr.com/photos/42987031@N00/188061516/in/photostream/), and it is"All rights reserved".

**Comment by pgrho** [comment]
And I think xUnit.net is more preferable than MSTest. (I was using MSTest in this repo as I had no idea about that the xunit test case needs to be defined in console app.)

**Comment by pgrho** [comment]
I'll merge PR if licenses of the test data is verified to be compatible with GPLv3. But I think excluding them is the better way. Downloading images from phash.org for private testing never infringe their copyrights, at least in Japanese law.

**Comment by pgrho** [comment]
I'm going to change TestApp's data to common directory such as `/data/blur`. That will enable you to write a test that depends on common test data.

And please send another PR that contains the bug fix only.

**Comment by pgrho** [comment]
Moved data directory to the root in #10. Please create new branch and copy [wildcarded element written in TestApp.csproj](https://github.com/pgrho/phash/blob/a7402384752e003e0e131e36d64f5f2856c38dd4/src/Shipwreck.Phash.TestApp/Shipwreck.Phash.TestApp.csproj#L22-L26).

**Comment by ThatRubenAguilar** [comment]
Yea, I definitely prefer n/xunit over mstest. The runners can all be included via nuget, which is super useful for deployment environment scenarios. Resharper integrates a nice UI element for the runners in VS as well.

I emailed phash about the licensing on the photos.

Since none of the current tests use the misc or rotd attacks, I'll use a photo I have rights to and do the compression and subsections.

**Comment by ThatRubenAguilar** [comment]
Regarding license of the test images, their response:

`
We are using the images under fair use provisions as outlined in US copyright law. Individual images may have their own copyrights and we make no guarantee on ownership nor do we assert any rights to the images.
`

So it does seem safer to have them download their phash set since they only considered US copyright law.

**Pull request closed without merging**
