### PR TITLE
Update to support dotnet core 3.1; Update nuget references; Add a new…

### PR DESCRIPTION
**Pull request by scegg**
Update to support dotnet core 3.1
Update nuget references
Add a new overload of method GetCrossCorrelation with length specified to limit the processing area with a larger range byte array provided.

### CODE REVIEW

**Comment by pgrho** [comment]
Thank you to submit patch. It looks good to me.

But I doubt that there is no difference between the output assembly targeting NETCOREAPP3.0 and NETCOREAPP3.1.
If the TargetFramework of a referenced assembly doesn't affect runtime performance, it should not be separated.

**Comment by scegg** [comment]
You are right.
Adding dotnet core 3.1 coz 3.0 is now end of life, replaced by 3.1 which is a LTS version.

**Comment by scegg** [comment]
https://devblogs.microsoft.com/dotnet/net-core-3-0-end-of-life/

**Comment by pgrho** [comment]
I see that NETCoreApp3.0 is EOL.
But the EOL is about its runtime. I suppose almost all the NETCoreApp3.0 APIs are also supported by newer runtimes.
I don't want to add tenth(lol) TargetFramework to Shipwreck.Phash if it brings no obvious difference.

### `CrossCorrelation.GetCrossCorrelation` overload

Please consider the following and create another pull request.

- Add the third overload to accept byte[] and its offsets. ie) `float GetCrossCorrelation(int startIndex1, byte[] coefficients1, int startIndex2, byte[] coefficients2, int length)`
- Add same methods to ImagePhash

**Comment by scegg** [comment]
I respect your decision.
My project will use my own fork instead, because some of components I used do not support 3.0 any more.

**Pull request closed without merging**
