### PR TITLE
Performance Stats to TestApp and Cached Activator Result

### PR DESCRIPTION
**Pull request by ThatRubenAguilar**

### CODE REVIEW

**Comment by pgrho** [comment]
How about adding a method to return IByteImageOperations in IByteImageWrapper?

**Comment by ThatRubenAguilar** [comment]
Would also work, can run it through the perf harness to see if it has an impact.

**Comment by ThatRubenAguilar** [comment]
It had a decent impact, about 13 seconds shaved off the total time or 10ms off each digest run. Updated the [results.](https://github.com/pgrho/phash/issues/5#issuecomment-354229926) I added it to this PR.

**Comment by pgrho** [comment]
[output.js#L21](https://github.com/ThatRubenAguilar/phash/blob/27ef0a1db761296ce55797c5e663065f63a24a83/src/Shipwreck.Phash.TestApp/output.js#L21) lacks `perf`. I'll fix it.

**Pull request merged**
